# Production LiveKit Server Configuration

port: 7880
log_level: info

rtc:
  tcp_port: 7881
  port_range_start: 50000
  port_range_end: 50100
  use_external_ip: true

# Room configuration
room:
  max_participants: 10
  empty_timeout: 300

# Disable TURN for simplified deployment
turn:
  enabled: false

# API keys from environment variables
keys:
  ${LIVEKIT_API_KEY}: ${LIVEKIT_API_SECRET} 